In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [6]:
b = np.array([[1,2,3],[4,5,6]])

In [7]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
c = np.zeros((5,5))

In [23]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
##Say you have two NumPy arrays how can you add the individual elements?
d = np.array([1,2,3])
e = np.array([4,5,6])

np.sum((d,e),axis=0)

array([5, 7, 9])

In [18]:
##Say you have two NumPy arrays how can you add the individual elements?
f = np.array([1,2,3])
g = np.array([4,5,6])

np.sum((f,g),axis=1)

array([ 6, 15])

In [22]:
## how can you get the 'N' largest values from a NumPy array? 
import numpy as np
x = np.array([12,43,2,100,54,5,68])


In [21]:

np.argsort(x)[-2:][::-1]

array([2, 5, 0, 1, 4, 6, 3])

In [24]:
x[np.argsort(x)[-2:][::-1]]

array([100,  68])